version: '3.9'
services:
    psql:
        image: postgres:15.3-alpine
        container_name: psql_transaction_demo
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: psql_db
            TZ: 'GMT+7'
            PGTZ: 'Asia/Bangkok'
        volumes:
            - ./data/db:/var/lib/postgresql/data
