// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID          int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32      `gorm:"column:user_id;not null" json:"user_id"`
	Address     *string    `gorm:"column:address" json:"address"`
	CreatedDate time.Time  `gorm:"column:created_date;not null;default:now()" json:"created_date"`
	UpdatedDate *time.Time `gorm:"column:updated_date" json:"updated_date"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
